### ISSUE TITLE
fs dependency not found

### ISSUE THREAD

**Issue by s-ferdie** [nuxt-community/dotenv-module#11]
I've follow the instructions to add the dotenv module.
When I run `npm run dev` I'm getting the following error:

This dependency was not found:

* fs in ./node_modules/@nuxtjs/dotenv/dist/index.js

To install it, you can run: npm install --save fs

Digging into this npm package its seems to be a security-holder package.
How to solve the error?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/dotenv-module/issues/c11">#c11</a>)</em></sub></div>

**Comment by tobiasfrei** [comment]
same issuse here for fs '0.0.1-security':

`This dependency was not found:

* fs in ./modules/read-dir.js

To install it, you can run: npm install --save fs
Server listening on http://127.0.0.1:3000`

node 8.9.4
npm 5.7.1

**Comment by JulienTant** [comment]
Can you guys help me reproduce this ? I've just tried with npm & yarn, I just can't reproduce :(

**Comment by phikhi** [comment]
I had that issue a while ago. Not in a nuxt project, but in a classic webpack app.
I found that trick somewhere on github that worked for me.

Try adding a `config.node` object inside the `build.extend` function of your `nuxt.config.js` :

```
build: {
    extend (config, { isDev, isClient }) {
 
       config.node: {
            fs: 'empty'
        }
 
       // ....
    }
}
```

After that if you get the same error, but for other dependencies, like `net` or `tls`. You can add them as well in the same config.node

**Comment by JulienTant** [comment]
@phikhi thank you so much for helping on this! ❤️

**Comment by JulienTant** [comment]
If you need more help about that, please reopen.

**Comment by kayyyy** [comment]
I solved this because added `dotenv` to the dependencies rather than devDependencies

**Comment by nicroto** [comment]
The snippet above is not syntactically correct. To save someone some time, here it is (of course the `...` are also not syntactically correct, they're just there to guide you where you place this):

```javascript
export default {

    ...

    build: {

        ...

        extend: function (config, {isDev, isClient}) {

            config.node = {

                fs: "empty"
            };
        }
    },

    ...
};
```

**Comment by phikhi** [comment]
@nicroto 

> The snippet above is not syntactically correct.

Why is that ?

**Comment by ValdoGhafoor** [comment]
@phikhi Because of you wrote "config.node: { " while it is "config.node = { "

**Comment by gomezmark** [comment]
@ktiedt 

same on my end. 
im using nuxt 2.4

Have you solve this?

**Comment by ktiedt** [comment]
@gomezmark I dropped Nuxt like it was hot.. have gotten very little support from the nuxt community regarding typescript, so it just wasn't worth my time to add a 3rd party project dependency into my workflow that has potential for massive delays in moving forward with upgrades.

**Comment by Samuelfaure** [comment]
Same error with nuxt 2.4.0
I might be wrong but this seems to do with the change of name of package 'fs'

**Comment by drewbaker** [comment]
I got this today on a fresh install too.
```
* fs in ./node_modules/dotenv/lib/main.js                                                                                       friendly-errors 12:16:43
```

**Comment by J0ssue** [comment]
this sucks I cant seem to figure it out 
have the same issue and theres no information about it anywhere
im using gridsome with vue and for some reason it doesnt work

**Comment by chadwtaylor** [comment]
Am hitting the same issue. npm-installing `fs` does not work and it's because it's already part of the node package. I also need `fs` to load a text file (eg: graphql schema).

**Comment by narrative1st** [comment]
Any word on this? Getting the same problem - trying to call `fs` within a plugin...

**Comment by drewbaker** [comment]
The solution by @nicroto above solved it for me.

**Comment by nirokun** [comment]
I had to restart the server after changing the config and it works for me. But, i have a problem calling "fs" functions on one node_modules. "fs.writeFileSync is not a function"

**Comment by jaslocum** [comment]
I could be totally wrong about this, but I believe that .js files are often run on the server and the client.  I believe that 'fs' will be available when code is running on the server and stubbed for security purposes when executed by the browser.  I used this.$isServer to conditionally determine if the code is being executed on the server or the browser.  This way, I avoid error's when the code is running on the client and 'fs' is not available.

**Comment by jaslocum** [comment]
I used the solution by @nicroto above as well.  However, fs.readFileSync was needed to read a cert in my nuxt.config.js.  fs.readFileSync was not defiled when the code was being run in the browser, but it worked fine when being executed on the node server.  I used the following to determine if the code was being executed on the server. I couldn't use this.$isServer because it wasn't defined yet when nuxt.config.js file is being executed.

if (typeof fs.readFileSync === 'function') {
   ... do stuff here
}

**Comment by abernh** [comment]
Maybe late to the party but here an alternative solution:
use [`fs-extra`](https://www.npmjs.com/package/fs-extra) package instead of `fs` (if you have the choice).

Adding `fs-extra` as a development dependency solved the issue for me on `gridsome` @J0ssue

**Comment by abernh** [comment]
via https://github.com/webpack-contrib/css-loader/issues/447
this seems not to be a nuxt issue but a webpack issue and it is "solved" by adding the "node:fs:empty"  solution to the webpack config parameters.

This also means @J0ssue that this issue is **solved for gridsome** by adding the following to the `gridsome.config.js`

```
module.exports = {
  ...
  configureWebpack: {
    node: {
      fs: "empty"
    }
  }
```

**Comment by KentChun33333** [comment]
had a similar issue, and solve by adding config.node = { fs: "empty"} into the build section in  nuxt.config.js. 

```
   build: {
    /*
    ** You can extend webpack config here
    */

    extend (config, ctx) {
        config.node = {
            fs: "empty"
        };
    }
  }
```

**Comment by bitttttten** [comment]
Also this happens if you just try and use `dotenv` in `nuxt.config.js`, like:

```js
import { config } from 'dotenv'

const { parsed } = config()

```

Which is also solves with the "fs empty" fix.

Is this a safe patch? What if some nuxt modules need fs? Is it better to guard this with:

```js
if (!ctx.isServer) config.node.fs = "empty"
```

Or something similar?

**Comment by heavenkiller2018** [comment]
I have the same problem, and fixed it by KentChun33333's resolution.

**Comment by anh-collab** [comment]
I have tried all the solutions mentioned but I still get fs.readFileSync() not a function error, which prevents my app from loading correctly. Anyone can help?

**Comment by donmb1** [comment]
after adding to `build` block I also get

```
dotenv.js?3b0e:10 Uncaught TypeError: fs.existsSync is not a function
    at Object.eval (dotenv.js?3b0e:10)
    at eval (dotenv.js:20)
    at Object../plugins/dotenv.js (app.js:1334)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at eval (index.js:56)
    at Module../.nuxt/index.js (app.js:251)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at Module.eval (client.js:55)
```

**Comment by nisharmultani** [comment]
add this in your nuxt-config.js
build: { extend (config, { isDev, isClient }) {
 
    config.node = {
         fs: 'empty'
     }
 }},
