### ISSUE TITLE
Use system process if .env file is not found

### ISSUE THREAD

**Issue by gijo-varghese** [nuxt-community/dotenv-module#12]
In our team, we would like to use `.env` file for local development. But it won't be committed to git. And while deploying it will take env variables from server. Right now when I add .env to .gitignore and when I try to build it from where, it throws an error saying that .env file is not found

**Comment by JulienTant** [comment]
We actually use system environment variable in priority : https://github.com/nuxt-community/dotenv-module/blob/master/src/index.js#L22

I also just published v1.1.1 that doesn't crash when .env file is not present.

Tell me if that helps !

**Comment by gijo-varghese** [comment]
Thanks. Let me try that :)

**Comment by gijo-varghese** [comment]
@JulienTant how can I use the variables from `.env` inside `nuxt.config.js`

**Comment by JulienTant** [comment]
yup it's documented in the readme. Actually it doesn't use the module but the dotenv package directly :)
