### ISSUE TITLE
Can't deploy to Netlify when using @Nuxt/dotenv

### ISSUE THREAD

**Issue by stuartjnelson** [nuxt-community/dotenv-module#13]
Hello!

I've been unable to deploy to Netlify when using the plugin. 

- "@nuxtjs/dotenv":  "^1.1.0"
- "nuxt": "^1.0.0"

```
modules: [
        ['@nuxtjs/dotenv']
]
```

[Netlfiy Error log when using the module](https://gist.github.com/stuartjnelson/d6785809c05df04d3c1f13988bf471ba)
[Netfliy log for successful deployment](https://gist.github.com/stuartjnelson/4094a35f2a1e9e74252e4a6dc174f7a5)

I've tried a whole bunch of different configurations inside `nuxt.config.js` but could'nt get anything to work. I don't get the issue when I generate the static site locally just when using Netlify. I have spoke to their support and they can't see the issue. I am wondering if its to do with the `NPM WARN` about missing optional dependencies? Let me know if you need anymore info!

**Comment by VitorLuizC** [comment]
Its because `@nuxtjs/dotenv` can't use system's variables when `.env` file is not found #12.

You can deploy `.env` file too. It's a bad practice, but works.

**Comment by stuartjnelson** [comment]
Thanks @VitorLuizC. I'll close for now then if that ticket is dealing with it. I think I've got a way round it as I just needed the `.env` for a Google analytics and I got a sneaky fix from [this issue ticket](https://github.com/nuxt-community/analytics-module/issues/10#issuecomment-375940614) for that use case

**Comment by JulienTant** [comment]
Hi, i've just published v1.1.1, now .env file is not mandatory !

**Comment by lmrarturo** [comment]
Hi guys, 

How are you implementing the variables without .env with Netlify?  for me is not working.

Help!

Thank you!

**Comment by devpaps** [comment]
> Hi guys,
> 
> How are you implementing the variables without .env with Netlify? for me is not working.
> 
> Help!
> 
> Thank you!

I also would like to know that.

**Comment by rutgerbakker95** [comment]
Hey guys,

Still not working for me

**Comment by Manage-Society** [comment]
Please need a solution ?
