### ISSUE TITLE
Cannot add private key

### ISSUE THREAD

**Issue by tamacroft** [nuxt-community/dotenv-module#14]
i have try : 
private_key="-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAAS....."
or
private_key:-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAAS...
or
private_key:'-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAAS....'

but result is Certificate object must contain a string "private_key" property.

**Comment by JulienTant** [comment]
I'm not sure how I can help you ?

That module is using this package to load variables from .env file : https://github.com/motdotla/dotenv. You should probably get help there !
