### ISSUE TITLE
variables not defined on init

### ISSUE THREAD

**Issue by javialon26** [nuxt-community/dotenv-module#2]
the environment variables are not defined at the beginning. I am using the nuxtjs / axios module where I configure:

```
baseURL: process.env.API_URL,
browserBaseURL: process.env.API_URL_BROWSER
```

with this config an error occurs:
```
TypeError: Cannot read property 'substr' of undefined
    at ModuleContainer.nuxtAxios (/home/javier/vms/twobvm/projects/cominghouse/node_modules/@nuxtjs/axios/lib/index.js:38:46)
```

thank you!

**Comment by JulienTant** [comment]
Hi,

The `dotenv-module` won't overload the environment variables of the process running your build.

So if you need to use variables from your `.env` file at this moment (and it looks like you do), just append `require('dotenv').config()` to your `nuxt.config.js` :

```js
require('dotenv').config()

module.exports = {
    // your usual nuxt config.
}
```

This will works thanks to the `dotenv` library provided by this module as a dependency. If you decided to ignore some values from your `.env` file in the module configuration, this won't apply here.

Hope this help, i will update the README file with this, it can be useful !

**Comment by KnutSv** [comment]
Not sure what I'm doing wrong, but I can't seem to access the `process.env`-variable no matter what I do.

process.env
```
API_BASE_URL=http://api.test.com
```

nuxt.config.js
```
require('dotenv').config()

module.exports = {
  ...
  mode: 'spa',
  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/dotenv',
  ],
  axios: {
    proxy: true
  },
  proxy: {
  	'/api/': process.env.API_BASE_URL
  }
}
```

In this setup `process.env.API_BASE_URL` is always: `undefined`

**Comment by willbrowningme** [comment]
@KnutSv to use the .env file in your nuxt.config.js you need to do the following:

```
// nuxt.config.js
const env = require('dotenv').config().parsed

module.exports = {
  ...
  mode: 'spa',
  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/dotenv',
  ],
  axios: {
    proxy: true
  },
  proxy: {
    '/api/': env.API_BASE_URL
  }
}
```

**Comment by KnutSv** [comment]
@willbrowningme Seems my problem was mainly that i named my `.env`-file `process.env` for some reason. Guess I got it mixed up when reading the doc. When I renamed it i and assigned it to a variable like you suggested (though i didn't need the `.parsed` part) it worked perfectly. Thanks :-)

**Comment by tetreault** [comment]
I've used the `dotenv` node module quite a bit but am trying this one for the first time. I'm having a similar issue. 

I have a .env file at the root of the project near nuxt.config.js. I have run `require('dotenv').config()`. When I console log out `process.env` I just get `{}`. 

My `nuxt.config.js` is: 

```
const pkg = require("./package");
require("dotenv").config();

module.exports = {
  mode: "universal",

  /*
  ** Headers of the page
  */
  head: {
    title: "Russian to English",
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { hid: "description", name: "description", content: pkg.description }
    ],
    link: [{ rel: "icon", type: "image/x-icon", href: "/favicon.ico" }]
  },

  /*
  ** Customize the progress-bar color
  */
  loading: { color: "#FFFFFF" },

  /*
  ** Global CSS
  */
  css: [],

  /*
  ** Plugins to load before mounting the App
  */
  plugins: [],

  /*
  ** Nuxt.js modules
  */
  modules: [
    // Doc: https://github.com/nuxt-community/axios-module#usage
    "@nuxtjs/axios",
    // Doc:https://github.com/nuxt-community/modules/tree/master/packages/bulma
    "@nuxtjs/bulma",
    ["@nuxtjs/dotenv"]
  ],
  /*
  ** Axios module configuration
  */
  axios: {
    // See https://github.com/nuxt-community/axios-module#options
  },

  /*
  ** Build configuration
  */
  build: {
    postcss: {
      plugins: {
        "postcss-cssnext": {
          features: {
            customProperties: false
          }
        }
      }
    },
    /*
    ** You can extend webpack config here
    */
    extend(config, ctx) {
      // Run ESLint on save
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: "pre",
          test: /\.(js|vue)$/,
          loader: "eslint-loader",
          exclude: /(node_modules)/
        });
      }
    }
  }
};
```

My `.env` file only has 3 entries in it, and for further context I'm running my console log statement inside `mounted()` in `pages/index.vue`.
