### ISSUE TITLE
Nuxt dotenv options require in nuxt-config.js doesn't work

### ISSUE THREAD

**Issue by aloiseau17** [nuxt-community/dotenv-module#24]
Hi,

I tried to use nuxt-dotenv with fileaname custom options like that:

```
modules: [
    ['@nuxtjs/dotenv', {
      filename: '.env.dev',
  }],
  ],
```
It's working fine in my app but not in my nuxt-config.js
I import dotenv at the top:

`require('dotenv').config()`

Before that I had to add the dotenv dependency to my package.json.
But the custom .env file wasn't read. Only .env is working.

**Comment by aloiseau17** [comment]
Sorry if my message doesn't fit the template. I didn't know.
It's more a bug than a question.
Can I have some help about it @JulienTant ?
Thank you.

**Comment by aloiseau17** [comment]
Ok, I just misunderstood the way to use .env inside nuxt-config.js

I just have to configure dot-env and not nuxtjs/dotenv when I require it inside nuxt-config.js
`require('dotenv').config({ path: '.env.dev' })`

**Comment by cuong-nguyen** [comment]
Sorry to bring the topic up again, but what's the purpose of

```['@nuxtjs/dotenv', { filename: '.env.prod' }]```

It never works for me with whatever value I set.

**Comment by cuong-nguyen** [comment]
For those who might wonder the same thing, this is the answer from a Discord contributor

> dotenv.config() merges your env variables into process env variables (process.env in node) while nuxt module also merges them to context.env.
Merging into process.env happens on running module so if you need them available earlier (for use in nuxt.config.js for example), you might want to additionally call dotenv.config() manually.
those two have different APIs regarding filename/path so follow documentation of respective module/pacakage
actually nuxt module doesn't call dotenv.config() so it won't merge your env variables to process.env the same way as dotenv would itself

**Comment by bradley-varol** [comment]
How can we use the `only: []` config option when using `require('dotenv').config()`  inside `nuxt.config.js`? I need to use some .env variables inside my nuxt config and others in my app but don't want to expose the whole .env file which `required('dotenv').config()` does...

**Comment by hilanmiao** [comment]
just like this！
```
require('dotenv').config()
['@nuxtjs/dotenv', { path: '.env.production', filename: '.env.production' }]
```
