### ISSUE TITLE
Env vars are empty after module install

### ISSUE THREAD

**Issue by megusta420** [nuxt-community/dotenv-module#27]
### Version

[1.3.0](https://github.com/dotenv-module/releases/tag/1.3.0)

### Reproduction link

[http://no.link](http://no.link)

### Steps to reproduce

1. yarn add @nuxtjs/dotenv
2. edit nuxt.config.js (modules property): https://pastebin.com/13Btdxyt
3. add some var to .env like this: SOMEKEY=SOME_KEY_VALUE
4. try to output value of process.env: https://pastebin.com/K4HAAuJq

### What is expected ?

output of .env file vars array

### What is actually happening?

empty object "{}"

nuxt version     "nuxt": "^2.0.0",

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/dotenv-module/issues/c21">#c21</a>)</em></sub></div>

**Comment by gkshi** [comment]
@megusta420 try to log particular property of process.env.

I've tried logging and got this:
`console.log(process.env) // returns {}`
`console.log(process.env.SOMEKEY) // returns SOME_KEY_VALUE`

**Comment by megusta420** [comment]
@gkshi yes you're right. Why that happens?

**Comment by megusta420** [comment]
Okay found explanation here: https://nuxtjs.org/api/configuration-env/
