### ISSUE TITLE
Empty only option array should result in nothing going into context.env

### ISSUE THREAD

**Issue by trentpeterson** [nuxt-community/dotenv-module#28]
### What problem does this feature solve?

Currently, if the `only` option is specified with an empty array, default logic is used and all values are placed into `context.env` and thus provided to the client.

I think that an empty array should signal that I do not want anything copied into `context.env`. If I do not specify an `only` option/array at all, I would expect the default behavior to apply and all values would be placed into  `context.env`.

As a workaround, I specify a name in the array that doesn't correspond to any key:
```js
['@nuxtjs/dotenv', { only: ['nothing'] }],
```

Related, I agree with [this comment](https://github.com/nuxt-community/dotenv-module/issues/7#issuecomment-373827568) on #7 that there should be a warning that **all values** are available on the client unless `only` is used.

### What does the proposed changes look like?

This configuration
```js
['@nuxtjs/dotenv', { only: [] }],
```
results in nothing in `.env` going into `context.env`.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/dotenv-module/issues/c22">#c22</a>)</em></sub></div>

**Comment by hartmut-co-uk** [comment]
Hi, not sure if this was working at some point in time, but with current `v1.4.1` 

With configuration
```
['@nuxtjs/dotenv', { only: [] }],
```
results in **nothing** in .env **being accessible** at all, neither in `context` nor `process`...

ref: https://github.com/nuxt-community/dotenv-module/issues/54
