### ISSUE TITLE
is it working with nuxt / express ?

### ISSUE THREAD

**Issue by pierre-aurele-martin** [nuxt-community/dotenv-module#6]
Hello,

Sorry to interrupt here but I really can not manage to achieve a simple thing (read process.env)

#1 - Only way I can read what's in my .env file is by 
`require('dotenv').config() `
in nuxt.config.js 

When I'm adding it as a module, it doesn't find anything even if .env is at the root...

#2 still in nuxt.config.js I define : 
```
 env: {
    test: process.env.TEST,
  },
```

#3 
In server/index.js I define : 

`const test = process.env.test `

And it's always undefined...

I've tried a lot and a lot of thing but I think I'm missing something here. Any help will be really appreciate !

thanks !

**Comment by artutra** [comment]
Same problem here

**Comment by JulienTant** [comment]
Hi,

I'm not sure that I understand your problem, so my answer might be out of topic or too global, just tell me if you need more information.

I see two topics here : 

- Use .env variables in a custom server (3)
- .env file doesn't load variables (1&2)

For the server stuff, this is completely out of the scope of this module. The module only load values into your context (https://nuxtjs.org/api/context/). If you need to use the values into your server, you must call `require('dotenv').config()` by hand.

For the second stuff, it would be more easy to debug with some code. The only thing that i can think of right know, is that if you put a key in your nuxt.config.js , it will **NOT** be overriden by your .env file values.

Here's the workflow :

1. Read nuxt.config.js env
2. load .env (or env variable)
3. if a variable is in .env but not in nuxt.config.js env, add it.

I really hope that helps.
