### ISSUE TITLE
is there way to keep secret key in .env? 

### ISSUE THREAD

**Issue by sprabowo** [nuxt-community/dotenv-module#7]
i see in my configuration that contain secret code in source code /_nuxt/app.1234132.js .env is loaded in. 

thanks

**Comment by JulienTant** [comment]
Hi,

The code is going to be executed on the client side, so the values have to be there.

You can use the `only`  option if you need to be choose precisely what will be there : https://github.com/nuxt-community/dotenv-module#only

**Comment by mootari** [comment]
@JulienTant I'd highly recommend to add a big fat warning to the readme that all vars from the .env will be exposed to the client by default.

I also noticed that defining `{only: []}` will whitelist all variables, because the array length is checked, not wether the `only` property is defined.
