### ISSUE TITLE
Hot reload if .env file changes are happening

### ISSUE THREAD

**Issue by pSchaub** [nuxt-community/dotenv-module#8]
Hot reloading is not working if you do a simple change on your `.env` file.

Steps to reproduce:
1. Start dev server (e.g. with `npm run dev` or `yarn run dev`)
2. Change something in your `.env` file

**Comment by mathieutu** [comment]
Linked to https://github.com/nuxt/nuxt.js/issues/2747.

**Comment by JulienTant** [comment]
I must say i have no clue about how to achieve this, because of the issue  @mathieutu shows us. For now, it's a "cant fix". sorry mate.
